/* tslint:disable */
/* eslint-disable */
/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It\'s designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.   ## Resources - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 67c9a1eda264be4cfe0bb2c76151f0aadf0862bc
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AttachmentMetaData
 */
export interface AttachmentMetaData {
    /**
     *
     * @type {number}
     * @memberof AttachmentMetaData
     */
    contentLength: number;
    /**
     *
     * @type {string}
     * @memberof AttachmentMetaData
     */
    contentType: string;
    /**
     *
     * @type {string}
     * @memberof AttachmentMetaData
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof AttachmentMetaData
     */
    name: string;
}

export function AttachmentMetaDataFromJSON(json: any): AttachmentMetaData {
    return AttachmentMetaDataFromJSONTyped(json, false);
}

export function AttachmentMetaDataFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): AttachmentMetaData {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        contentLength: json['contentLength'],
        contentType: json['contentType'],
        id: json['id'],
        name: json['name'],
    };
}

export function AttachmentMetaDataToJSON(
    value?: AttachmentMetaData | null
): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        contentLength: value.contentLength,
        contentType: value.contentType,
        id: value.id,
        name: value.name,
    };
}
