/* tslint:disable */
/* eslint-disable */
/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It\'s designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.   ## Resources - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 67c9a1eda264be4cfe0bb2c76151f0aadf0862bc
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BasicAuthOptions,
    BasicAuthOptionsFromJSON,
    BasicAuthOptionsFromJSONTyped,
    BasicAuthOptionsToJSON,
} from './';

/**
 * Options for creating a webhook. Webhooks can be attached to inboxes and MailSlurp will POST a webhook payload to the URL specified whenever the inbox receives an email. Webhooks are great for processing many inbound emails.
 * @export
 * @interface CreateWebhookOptions
 */
export interface CreateWebhookOptions {
    /**
     *
     * @type {BasicAuthOptions}
     * @memberof CreateWebhookOptions
     */
    basicAuth?: BasicAuthOptions;
    /**
     * Optional name for the webhook
     * @type {string}
     * @memberof CreateWebhookOptions
     */
    name?: string;
    /**
     * Public URL on your server that MailSlurp can post WebhookNotification payload to when an email is received. The payload of the submitted JSON is described by https://api.mailslurp.com/schemas/webhook-payload
     * @type {string}
     * @memberof CreateWebhookOptions
     */
    url?: string;
}

export function CreateWebhookOptionsFromJSON(json: any): CreateWebhookOptions {
    return CreateWebhookOptionsFromJSONTyped(json, false);
}

export function CreateWebhookOptionsFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): CreateWebhookOptions {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        basicAuth: !exists(json, 'basicAuth')
            ? undefined
            : BasicAuthOptionsFromJSON(json['basicAuth']),
        name: !exists(json, 'name') ? undefined : json['name'],
        url: !exists(json, 'url') ? undefined : json['url'],
    };
}

export function CreateWebhookOptionsToJSON(
    value?: CreateWebhookOptions | null
): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        basicAuth: BasicAuthOptionsToJSON(value.basicAuth),
        name: value.name,
        url: value.url,
    };
}
