/* tslint:disable */
/* eslint-disable */
/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It\'s designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.   ## Resources - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 67c9a1eda264be4cfe0bb2c76151f0aadf0862bc
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MatchOption,
    MatchOptionFromJSON,
    MatchOptionFromJSONTyped,
    MatchOptionToJSON,
} from './';

/**
 * Optional filter for matching emails based on fields
 * @export
 * @interface MatchOptions
 */
export interface MatchOptions {
    /**
     * 1 or more match options. Options are additive so if one does not match the email is excluded from results
     * @type {Array<MatchOption>}
     * @memberof MatchOptions
     */
    matches?: Array<MatchOption>;
}

export function MatchOptionsFromJSON(json: any): MatchOptions {
    return MatchOptionsFromJSONTyped(json, false);
}

export function MatchOptionsFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): MatchOptions {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        matches: !exists(json, 'matches')
            ? undefined
            : (json['matches'] as Array<any>).map(MatchOptionFromJSON),
    };
}

export function MatchOptionsToJSON(value?: MatchOptions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        matches:
            value.matches === undefined
                ? undefined
                : (value.matches as Array<any>).map(MatchOptionToJSON),
    };
}
