/* tslint:disable */
/* eslint-disable */
/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It\'s designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.   ## Resources - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 67c9a1eda264be4cfe0bb2c76151f0aadf0862bc
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Options for uploading files for attachments. When sending emails with the API that require attachments first upload each attachment. Then use the returned attachment ID in your SendEmailOptions when sending an email. This way you can use attachments multiple times once they have been uploaded.
 * @export
 * @interface UploadAttachmentOptions
 */
export interface UploadAttachmentOptions {
    /**
     * Base64 encoded string of file contents
     * @type {string}
     * @memberof UploadAttachmentOptions
     */
    base64Contents?: string;
    /**
     * Optional contentType for file. For instance `application/pdf`
     * @type {string}
     * @memberof UploadAttachmentOptions
     */
    contentType?: string;
    /**
     * Optional filename to save upload with
     * @type {string}
     * @memberof UploadAttachmentOptions
     */
    filename?: string;
}

export function UploadAttachmentOptionsFromJSON(
    json: any
): UploadAttachmentOptions {
    return UploadAttachmentOptionsFromJSONTyped(json, false);
}

export function UploadAttachmentOptionsFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): UploadAttachmentOptions {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        base64Contents: !exists(json, 'base64Contents')
            ? undefined
            : json['base64Contents'],
        contentType: !exists(json, 'contentType')
            ? undefined
            : json['contentType'],
        filename: !exists(json, 'filename') ? undefined : json['filename'],
    };
}

export function UploadAttachmentOptionsToJSON(
    value?: UploadAttachmentOptions | null
): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        base64Contents: value.base64Contents,
        contentType: value.contentType,
        filename: value.filename,
    };
}
