/* tslint:disable */
/* eslint-disable */
/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It\'s designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.   ## Resources - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 67c9a1eda264be4cfe0bb2c76151f0aadf0862bc
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    EmailPreview,
    EmailPreviewFromJSON,
    EmailPreviewToJSON,
    Inbox,
    InboxFromJSON,
    InboxToJSON,
    PageEmailPreview,
    PageEmailPreviewFromJSON,
    PageEmailPreviewToJSON,
    PageInboxProjection,
    PageInboxProjectionFromJSON,
    PageInboxProjectionToJSON,
    SendEmailOptions,
    SendEmailOptionsFromJSON,
    SendEmailOptionsToJSON,
    SetInboxFavouritedOptions,
    SetInboxFavouritedOptionsFromJSON,
    SetInboxFavouritedOptionsToJSON,
    UpdateInboxOptions,
    UpdateInboxOptionsFromJSON,
    UpdateInboxOptionsToJSON,
} from '../models';

export interface CreateInboxRequest {
    description?: string;
    emailAddress?: string;
    expiresAt?: Date;
    favourite?: boolean;
    name?: string;
    tags?: Array<string>;
}

export interface DeleteInboxRequest {
    inboxId: string;
}

export interface GetAllInboxesRequest {
    favourite?: boolean;
    page?: number;
    search?: string;
    size?: number;
    sort?: GetAllInboxesSortEnum;
}

export interface GetEmailsRequest {
    inboxId: string;
    limit?: number;
    minCount?: number;
    retryTimeout?: number;
    since?: Date;
    sort?: GetEmailsSortEnum;
}

export interface GetInboxRequest {
    inboxId: string;
}

export interface GetInboxEmailsPaginatedRequest {
    inboxId: string;
    page?: number;
    size?: number;
    sort?: GetInboxEmailsPaginatedSortEnum;
}

export interface SendEmailRequest {
    inboxId: string;
    sendEmailOptions?: SendEmailOptions;
}

export interface SetInboxFavouritedRequest {
    inboxId: string;
    setInboxFavouritedOptions: SetInboxFavouritedOptions;
}

export interface UpdateInboxRequest {
    inboxId: string;
    updateInboxOptions: UpdateInboxOptions;
}

/**
 * no description
 */
export class InboxControllerApi extends runtime.BaseAPI {
    /**
     * Create a new inbox and with a randomized email address to send and receive from. Pass emailAddress parameter if you wish to use a specific email address. Creating an inbox is required before sending or receiving emails. If writing tests it is recommended that you create a new inbox during each test method so that it is unique and empty.
     * Create an Inbox (email address)
     */
    async createInboxRaw(
        requestParameters: CreateInboxRequest
    ): Promise<runtime.ApiResponse<Inbox>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.description !== undefined) {
            queryParameters['description'] = requestParameters.description;
        }

        if (requestParameters.emailAddress !== undefined) {
            queryParameters['emailAddress'] = requestParameters.emailAddress;
        }

        if (requestParameters.expiresAt !== undefined) {
            queryParameters[
                'expiresAt'
            ] = (requestParameters.expiresAt as any).toISOString();
        }

        if (requestParameters.favourite !== undefined) {
            queryParameters['favourite'] = requestParameters.favourite;
        }

        if (requestParameters.name !== undefined) {
            queryParameters['name'] = requestParameters.name;
        }

        if (requestParameters.tags) {
            queryParameters['tags'] = requestParameters.tags;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['x-api-key'] = this.configuration.apiKey(
                'x-api-key'
            ); // API_KEY authentication
        }

        const response = await this.request({
            path: `/inboxes`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, jsonValue =>
            InboxFromJSON(jsonValue)
        );
    }

    /**
     * Create a new inbox and with a randomized email address to send and receive from. Pass emailAddress parameter if you wish to use a specific email address. Creating an inbox is required before sending or receiving emails. If writing tests it is recommended that you create a new inbox during each test method so that it is unique and empty.
     * Create an Inbox (email address)
     */
    async createInbox(requestParameters: CreateInboxRequest): Promise<Inbox> {
        const response = await this.createInboxRaw(requestParameters);
        return await response.value();
    }

    /**
     * Permanently delete all inboxes and associated email addresses. This will also delete all emails within the inboxes. Be careful as inboxes cannot be recovered once deleted. Note: deleting inboxes will not impact your usage limits. Monthly inbox creation limits are based on how many inboxes were created in the last 30 days, not how many inboxes you currently have.
     * Delete all inboxes
     */
    async deleteAllInboxesRaw(): Promise<runtime.ApiResponse<void>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['x-api-key'] = this.configuration.apiKey(
                'x-api-key'
            ); // API_KEY authentication
        }

        const response = await this.request({
            path: `/inboxes`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Permanently delete all inboxes and associated email addresses. This will also delete all emails within the inboxes. Be careful as inboxes cannot be recovered once deleted. Note: deleting inboxes will not impact your usage limits. Monthly inbox creation limits are based on how many inboxes were created in the last 30 days, not how many inboxes you currently have.
     * Delete all inboxes
     */
    async deleteAllInboxes(): Promise<void> {
        await this.deleteAllInboxesRaw();
    }

    /**
     * Permanently delete an inbox and associated email address aswell as all emails within the given inbox. This action cannot be undone. Note: deleting an inbox will not affect your account usage. Monthly inbox usage is based on how many inboxes you create within 30 days, not how many exist at time of request.
     * Delete inbox
     */
    async deleteInboxRaw(
        requestParameters: DeleteInboxRequest
    ): Promise<runtime.ApiResponse<void>> {
        if (
            requestParameters.inboxId === null ||
            requestParameters.inboxId === undefined
        ) {
            throw new runtime.RequiredError(
                'inboxId',
                'Required parameter requestParameters.inboxId was null or undefined when calling deleteInbox.'
            );
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['x-api-key'] = this.configuration.apiKey(
                'x-api-key'
            ); // API_KEY authentication
        }

        const response = await this.request({
            path: `/inboxes/{inboxId}`.replace(
                `{${'inboxId'}}`,
                encodeURIComponent(String(requestParameters.inboxId))
            ),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Permanently delete an inbox and associated email address aswell as all emails within the given inbox. This action cannot be undone. Note: deleting an inbox will not affect your account usage. Monthly inbox usage is based on how many inboxes you create within 30 days, not how many exist at time of request.
     * Delete inbox
     */
    async deleteInbox(requestParameters: DeleteInboxRequest): Promise<void> {
        await this.deleteInboxRaw(requestParameters);
    }

    /**
     * List inboxes in paginated form. Allows for page index, page size, and sort direction. Can also filter by favourited or email address like pattern.
     * List Inboxes Paginated
     */
    async getAllInboxesRaw(
        requestParameters: GetAllInboxesRequest
    ): Promise<runtime.ApiResponse<PageInboxProjection>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.favourite !== undefined) {
            queryParameters['favourite'] = requestParameters.favourite;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.search !== undefined) {
            queryParameters['search'] = requestParameters.search;
        }

        if (requestParameters.size !== undefined) {
            queryParameters['size'] = requestParameters.size;
        }

        if (requestParameters.sort !== undefined) {
            queryParameters['sort'] = requestParameters.sort;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['x-api-key'] = this.configuration.apiKey(
                'x-api-key'
            ); // API_KEY authentication
        }

        const response = await this.request({
            path: `/inboxes/paginated`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, jsonValue =>
            PageInboxProjectionFromJSON(jsonValue)
        );
    }

    /**
     * List inboxes in paginated form. Allows for page index, page size, and sort direction. Can also filter by favourited or email address like pattern.
     * List Inboxes Paginated
     */
    async getAllInboxes(
        requestParameters: GetAllInboxesRequest
    ): Promise<PageInboxProjection> {
        const response = await this.getAllInboxesRaw(requestParameters);
        return await response.value();
    }

    /**
     * List emails that an inbox has received. Only emails that are sent to the inbox\'s email address will appear in the inbox. It may take several seconds for any email you send to an inbox\'s email address to appear in the inbox. To make this endpoint wait for a minimum number of emails use the `minCount` parameter. The server will retry the inbox database until the `minCount` is satisfied or the `retryTimeout` is reached
     * Get emails in an Inbox
     */
    async getEmailsRaw(
        requestParameters: GetEmailsRequest
    ): Promise<runtime.ApiResponse<Array<EmailPreview>>> {
        if (
            requestParameters.inboxId === null ||
            requestParameters.inboxId === undefined
        ) {
            throw new runtime.RequiredError(
                'inboxId',
                'Required parameter requestParameters.inboxId was null or undefined when calling getEmails.'
            );
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.minCount !== undefined) {
            queryParameters['minCount'] = requestParameters.minCount;
        }

        if (requestParameters.retryTimeout !== undefined) {
            queryParameters['retryTimeout'] = requestParameters.retryTimeout;
        }

        if (requestParameters.since !== undefined) {
            queryParameters[
                'since'
            ] = (requestParameters.since as any).toISOString();
        }

        if (requestParameters.sort !== undefined) {
            queryParameters['sort'] = requestParameters.sort;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['x-api-key'] = this.configuration.apiKey(
                'x-api-key'
            ); // API_KEY authentication
        }

        const response = await this.request({
            path: `/inboxes/{inboxId}/emails`.replace(
                `{${'inboxId'}}`,
                encodeURIComponent(String(requestParameters.inboxId))
            ),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, jsonValue =>
            jsonValue.map(EmailPreviewFromJSON)
        );
    }

    /**
     * List emails that an inbox has received. Only emails that are sent to the inbox\'s email address will appear in the inbox. It may take several seconds for any email you send to an inbox\'s email address to appear in the inbox. To make this endpoint wait for a minimum number of emails use the `minCount` parameter. The server will retry the inbox database until the `minCount` is satisfied or the `retryTimeout` is reached
     * Get emails in an Inbox
     */
    async getEmails(
        requestParameters: GetEmailsRequest
    ): Promise<Array<EmailPreview>> {
        const response = await this.getEmailsRaw(requestParameters);
        return await response.value();
    }

    /**
     * Returns an inbox\'s properties, including its email address and ID.
     * Get Inbox
     */
    async getInboxRaw(
        requestParameters: GetInboxRequest
    ): Promise<runtime.ApiResponse<Inbox>> {
        if (
            requestParameters.inboxId === null ||
            requestParameters.inboxId === undefined
        ) {
            throw new runtime.RequiredError(
                'inboxId',
                'Required parameter requestParameters.inboxId was null or undefined when calling getInbox.'
            );
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['x-api-key'] = this.configuration.apiKey(
                'x-api-key'
            ); // API_KEY authentication
        }

        const response = await this.request({
            path: `/inboxes/{inboxId}`.replace(
                `{${'inboxId'}}`,
                encodeURIComponent(String(requestParameters.inboxId))
            ),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, jsonValue =>
            InboxFromJSON(jsonValue)
        );
    }

    /**
     * Returns an inbox\'s properties, including its email address and ID.
     * Get Inbox
     */
    async getInbox(requestParameters: GetInboxRequest): Promise<Inbox> {
        const response = await this.getInboxRaw(requestParameters);
        return await response.value();
    }

    /**
     * Get a paginated list of emails in an inbox. Does not hold connections open.
     * Get inbox emails paginated
     */
    async getInboxEmailsPaginatedRaw(
        requestParameters: GetInboxEmailsPaginatedRequest
    ): Promise<runtime.ApiResponse<PageEmailPreview>> {
        if (
            requestParameters.inboxId === null ||
            requestParameters.inboxId === undefined
        ) {
            throw new runtime.RequiredError(
                'inboxId',
                'Required parameter requestParameters.inboxId was null or undefined when calling getInboxEmailsPaginated.'
            );
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.size !== undefined) {
            queryParameters['size'] = requestParameters.size;
        }

        if (requestParameters.sort !== undefined) {
            queryParameters['sort'] = requestParameters.sort;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['x-api-key'] = this.configuration.apiKey(
                'x-api-key'
            ); // API_KEY authentication
        }

        const response = await this.request({
            path: `/inboxes/{inboxId}/emails/paginated`.replace(
                `{${'inboxId'}}`,
                encodeURIComponent(String(requestParameters.inboxId))
            ),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, jsonValue =>
            PageEmailPreviewFromJSON(jsonValue)
        );
    }

    /**
     * Get a paginated list of emails in an inbox. Does not hold connections open.
     * Get inbox emails paginated
     */
    async getInboxEmailsPaginated(
        requestParameters: GetInboxEmailsPaginatedRequest
    ): Promise<PageEmailPreview> {
        const response = await this.getInboxEmailsPaginatedRaw(
            requestParameters
        );
        return await response.value();
    }

    /**
     * List the inboxes you have created
     * List Inboxes / Email Addresses
     */
    async getInboxesRaw(): Promise<runtime.ApiResponse<Array<Inbox>>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['x-api-key'] = this.configuration.apiKey(
                'x-api-key'
            ); // API_KEY authentication
        }

        const response = await this.request({
            path: `/inboxes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, jsonValue =>
            jsonValue.map(InboxFromJSON)
        );
    }

    /**
     * List the inboxes you have created
     * List Inboxes / Email Addresses
     */
    async getInboxes(): Promise<Array<Inbox>> {
        const response = await this.getInboxesRaw();
        return await response.value();
    }

    /**
     * Send an email from an inbox\'s email address.  The request body should contain the `SendEmailOptions` that include recipients, attachments, body etc. See `SendEmailOptions` for all available properties. Note the `inboxId` refers to the inbox\'s id not the inbox\'s email address. See https://www.mailslurp.com/guides/ for more information on how to send emails.
     * Send Email
     */
    async sendEmailRaw(
        requestParameters: SendEmailRequest
    ): Promise<runtime.ApiResponse<void>> {
        if (
            requestParameters.inboxId === null ||
            requestParameters.inboxId === undefined
        ) {
            throw new runtime.RequiredError(
                'inboxId',
                'Required parameter requestParameters.inboxId was null or undefined when calling sendEmail.'
            );
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['x-api-key'] = this.configuration.apiKey(
                'x-api-key'
            ); // API_KEY authentication
        }

        const response = await this.request({
            path: `/inboxes/{inboxId}`.replace(
                `{${'inboxId'}}`,
                encodeURIComponent(String(requestParameters.inboxId))
            ),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SendEmailOptionsToJSON(requestParameters.sendEmailOptions),
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Send an email from an inbox\'s email address.  The request body should contain the `SendEmailOptions` that include recipients, attachments, body etc. See `SendEmailOptions` for all available properties. Note the `inboxId` refers to the inbox\'s id not the inbox\'s email address. See https://www.mailslurp.com/guides/ for more information on how to send emails.
     * Send Email
     */
    async sendEmail(requestParameters: SendEmailRequest): Promise<void> {
        await this.sendEmailRaw(requestParameters);
    }

    /**
     * Set and return new favourite state for an inbox
     * Set inbox favourited state
     */
    async setInboxFavouritedRaw(
        requestParameters: SetInboxFavouritedRequest
    ): Promise<runtime.ApiResponse<Inbox>> {
        if (
            requestParameters.inboxId === null ||
            requestParameters.inboxId === undefined
        ) {
            throw new runtime.RequiredError(
                'inboxId',
                'Required parameter requestParameters.inboxId was null or undefined when calling setInboxFavourited.'
            );
        }

        if (
            requestParameters.setInboxFavouritedOptions === null ||
            requestParameters.setInboxFavouritedOptions === undefined
        ) {
            throw new runtime.RequiredError(
                'setInboxFavouritedOptions',
                'Required parameter requestParameters.setInboxFavouritedOptions was null or undefined when calling setInboxFavourited.'
            );
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['x-api-key'] = this.configuration.apiKey(
                'x-api-key'
            ); // API_KEY authentication
        }

        const response = await this.request({
            path: `/inboxes/{inboxId}/favourite`.replace(
                `{${'inboxId'}}`,
                encodeURIComponent(String(requestParameters.inboxId))
            ),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SetInboxFavouritedOptionsToJSON(
                requestParameters.setInboxFavouritedOptions
            ),
        });

        return new runtime.JSONApiResponse(response, jsonValue =>
            InboxFromJSON(jsonValue)
        );
    }

    /**
     * Set and return new favourite state for an inbox
     * Set inbox favourited state
     */
    async setInboxFavourited(
        requestParameters: SetInboxFavouritedRequest
    ): Promise<Inbox> {
        const response = await this.setInboxFavouritedRaw(requestParameters);
        return await response.value();
    }

    /**
     * Update editable fields on an inbox
     * Update Inbox
     */
    async updateInboxRaw(
        requestParameters: UpdateInboxRequest
    ): Promise<runtime.ApiResponse<Inbox>> {
        if (
            requestParameters.inboxId === null ||
            requestParameters.inboxId === undefined
        ) {
            throw new runtime.RequiredError(
                'inboxId',
                'Required parameter requestParameters.inboxId was null or undefined when calling updateInbox.'
            );
        }

        if (
            requestParameters.updateInboxOptions === null ||
            requestParameters.updateInboxOptions === undefined
        ) {
            throw new runtime.RequiredError(
                'updateInboxOptions',
                'Required parameter requestParameters.updateInboxOptions was null or undefined when calling updateInbox.'
            );
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['x-api-key'] = this.configuration.apiKey(
                'x-api-key'
            ); // API_KEY authentication
        }

        const response = await this.request({
            path: `/inboxes/{inboxId}`.replace(
                `{${'inboxId'}}`,
                encodeURIComponent(String(requestParameters.inboxId))
            ),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateInboxOptionsToJSON(
                requestParameters.updateInboxOptions
            ),
        });

        return new runtime.JSONApiResponse(response, jsonValue =>
            InboxFromJSON(jsonValue)
        );
    }

    /**
     * Update editable fields on an inbox
     * Update Inbox
     */
    async updateInbox(requestParameters: UpdateInboxRequest): Promise<Inbox> {
        const response = await this.updateInboxRaw(requestParameters);
        return await response.value();
    }
}

/**
 * @export
 * @enum {string}
 */
export enum GetAllInboxesSortEnum {
    ASC = 'ASC',
    DESC = 'DESC',
}
/**
 * @export
 * @enum {string}
 */
export enum GetEmailsSortEnum {
    ASC = 'ASC',
    DESC = 'DESC',
}
/**
 * @export
 * @enum {string}
 */
export enum GetInboxEmailsPaginatedSortEnum {
    ASC = 'ASC',
    DESC = 'DESC',
}
